title: "Machine Learning for the Geosciences: Winter 2026"
description: Course materials for the Winter 2026 iteration of ESS 469/569.
remote_theme: clayh53/tufte-jekyll
plugins:
- jekyll-remote-theme
